---
fromAddress: akrobinson74@gmail.com

logging:
  level: INFO
  appenders:
  - type: console
    logFormat:
    threshold: ALL


server:
  applicationConnectors:
    - type: http
      port: 8081
  adminConnectors:
    - type: http
      port: 8082

swagger:
  resourcePackage: com.smacc.codingchallenge.api.rest